### PR TITLE
Replaced TinyMCE7 with TinyMCE6

### PR DESCRIPTION
**Pull request by fballiano**
I couldn't test an installation with this but I know for sure tiny6 is compatible with tiny7 (did the same tests for my own projects)

### CODE REVIEW

**Comment by rhoerr** [comment]
Awesome, thank you.

I would like to also incorporate these fixes to upstream bugs introduced by the tiny7 upgrade:
https://github.com/magento/magento2/pull/39253
https://github.com/magento/magento2/pull/39258

And possibly incorporate changes from https://github.com/magefan/module-wysiwyg-advanced/compare/master...ivanhrytsaim:module-wysiwyg-advanced:12062-TinyMCE-support-upgrade to enable the font size option (also an upstream regression with tiny7).

**Comment by fballiano** [comment]
> I would like to also incorporate these fixes to upstream bugs introduced by the tiny7 upgrade: [magento/magento2#39253](https://github.com/magento/magento2/pull/39253) [magento/magento2#39258](https://github.com/magento/magento2/pull/39258)

done

> And possibly incorporate changes from [magefan/module-wysiwyg-advanced@master...ivanhrytsaim:module-wysiwyg-advanced:12062-TinyMCE-support-upgrade](https://github.com/magefan/module-wysiwyg-advanced/compare/master...ivanhrytsaim:module-wysiwyg-advanced:12062-TinyMCE-support-upgrade) to enable the font size option (also an upstream regression with tiny7).

but where should I put that file? I can't find anything related to that code in our repo

**Comment by rhoerr** [comment]
> but where should I put that file? I can't find anything related to that code in our repo

I'll investigate that later -- either it's hiding somewhere in the core WYSIWYG code, or core doesn't initialize these settings at all currently.

**Comment by rhoerr** [comment]
I found where core handles that config: [\Magento\Cms\Model\Wysiwyg\DefaultConfigProvider::getConfig](https://github.com/mage-os/mageos-magento2/blob/2.4-develop/app/code/Magento/Cms/Model/Wysiwyg/DefaultConfigProvider.php)

Possibly related test config: https://github.com/mage-os/mageos-magento2/blob/2.4-develop/app/code/Magento/Cms/Test/Mftf/Section/TinyMCESection/TinyMCESection.xml (although we don't use the MFTF test suite ourselves)

**Comment by fballiano** [comment]
it could be this file: https://github.com/mage-os/mageos-magento2/blob/2.4-develop/app/code/Magento/Ui/view/base/web/js/form/element/wysiwyg.js and https://github.com/fballiano/mageos-ryan/blob/18dd197b5b9866faab510d61432e3ffd1b53bd4a/lib/web/mage/adminhtml/wysiwyg/tiny_mce/tinymceAdapter.js#L4 but I don't have the skills and the tools at the moment to dig more.

I'm not sure we should block this to add this fix/feature

**Comment by rhoerr** [comment]
It should probably be a separate PR either way. We can process this as-is. Thanks Fabrizio!

**Comment by rhoerr** [comment]
The Tiny 6 files look good to me. I fixed a typo in the config XML. Unfortunately it's not actually working for me as of yet. I get this in console on loading the editor for a CMS page:

```
editor_plugin.js:14 Uncaught TypeError: tinymce.create is not a function
    at editor_plugin.js:14:17
    at tinymceAdapter.js:92:29
    at Object.execCb (require.js:1696:33)
    at context.execCb (resolver.js:156:31)
    at Module.check (require.js:883:51)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
```

So something isn't wired up. I haven't investigated far enough yet to determine what.

This might be specific to Page Builder. It seems to load on product edit.

**Comment by rhoerr** [comment]
Disregard that last! My mistake, had out of date requirejs-config without the updated tinymce reference. Found that on code review, retested, works on Page Builder too now. Going to approve and merge.

**Review by rhoerr — APPROVED** [review]
Thank you, looks good and checks out on QA.

**Comment by fballiano** [comment]
@rhoerr so sorry about the tag mismatch!! weird! phpstorm changes the closing tags automatically 🧐

**Pull request merged**
